server:
  port: ${PORT:8081}
  servlet:
    context-path: /api/v1
spring:
  application:
    name: userRoles
  datasource:
    url: ${DB_URL:jdbc:h2:mem:test}
    driverClassName: org.h2.Driver
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true


